openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
servers:
  - url: /api
    description: APIのベースパス
paths:
  /tasks:
    $ref: '../schemas/paths/tasks.yaml'
  /tasks/{taskId}:
    $ref: '../schemas/paths/task.yaml'
  /tasks/reorder:
    $ref: '../schemas/paths/reorder.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: '../schemas/components/schemas.yaml'
  # responses:
  #   $ref: '../schemas/components/responses.yaml' 